version: "3"

services:
  
  backend:
    restart: always
    image: infisical/infisical:${SOFTWARE_VERSION_TAG}
    ports:
      - 172.17.0.1:6443:8080
    env_file: ./.env
    environment:
      - NODE_ENV=production
      - DB_CONNECTION_URI=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}

  redis:
    image: redis
    env_file: .env
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    #ports:
    # - 6379:6379
    volumes:
      - ./redis_data:/data
      
  db-migration:
    image: infisical/infisical:${SOFTWARE_VERSION_TAG}
    env_file: .env
    environment:
      - DB_CONNECTION_URI=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    command: npm run migration:latest
    
    
  db:
    image: postgres:16-alpine
    restart: always
    env_file: .env
    volumes:
      - ./pg_data:/var/lib/postgresql/data
